feat: add support for source-base option
evanw/esbuild pull request #2554
Opened 2022-09-16 12:35 UTC by Patrick-Beuks

Add support-base as option. This can be used when your output file is not in at the base where you want to calculate your sources from

This is inline with settings from other bundlers:
https://webpack.js.org/plugins/source-map-dev-tool-plugin/ -> fileContext
https://parceljs.org/plugin-system/source-maps/ -> projectRoot
https://github.com/terser/terser -> source-map -> base

Fixes #2218

2022-09-16 12:47 UTC, Patrick-Beuks commented on internal/bundler/linker.go
> +    }
If there is a better way to do this if statement let me know. This is the first time writing go

2022-09-16 12:47 UTC, Patrick-Beuks commented on internal/bundler/linker.go
> +        }
Let me know if there is a better way to handle errors

2022-09-19 09:59 UTC, Patrick-Beuks commented
Might fix the following issues
#2401 #2283

2023-11-13 23:07 UTC, jessica-jorgenson requested changes
Spelling

2023-11-13 23:07 UTC, jessica-jorgenson commented on internal/bundler/linker.go
> +        var succes bool
```suggestion
        var success bool
```

2023-11-13 23:07 UTC, jessica-jorgenson commented on internal/bundler/linker.go
> +        sourceAbsDir, succes = c.fs.Abs(c.options.SourceBase)
```suggestion
        sourceAbsDir, success = c.fs.Abs(c.options.SourceBase)
```

2023-11-13 23:07 UTC, jessica-jorgenson commented on internal/bundler/linker.go
> +        if !succes {
```suggestion
        if !success {
```

2023-11-15 12:09 UTC, Patrick-Beuks commented
Due to lack of time to update PR to resolve merge conflicts and update to latest changes I am closing this PR.

If someone wants to pick this PR up and needs information how/why this works. You can contact me.

2023-11-15 12:09 UTC, closed without merging