types: update Deno NS types
evanw/esbuild pull request #2994
Opened 2023-03-15 10:30 UTC by jsejcksn

This PR updates the Deno namespace types.

It looks like the current types are from [the initial feature commit](https://github.com/evanw/esbuild/pull/1145/commits/cfedc07472e32b5d812107d598a644e0c7dceb10) from a couple of years ago at `2021-04-13T09:38:00Z`.

It's not obvious to me how this types file was created: AFAICT it's not a byte-exact representation of any artifact from a commit in the history of the Deno repository, but it's pretty close to [this one from the `1.8.3` release](https://github.com/denoland/deno/blob/v1.8.3/cli/dts/lib.deno.ns.d.ts) which was [the latest release at the time of the commit](https://github.com/denoland/deno/tags?after=v1.9.1).

<details>
<summary>
Examining the diff shows changes in insignificant whitespace and that the <a href="https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html">TypeScript triple-slash directives</a> were converted to plain comments:
</summary>

<pre><code>&gt; diff <a href="https://raw.githubusercontent.com/denoland/deno/v1.8.3/cli/dts/lib.deno.ns.d.ts">deno_version</a> <a href="https://raw.githubusercontent.com/evanw/esbuild/0c8a0a901d9a6c7bbff9b4dd347c8a3f65f6c6dd/lib/deno/lib.deno.ns.d.ts">esbuild_version</a></code></pre>

```diff
3,4c3,4
< /// <reference no-default-lib="true" />
< /// <reference lib="esnext" />
---
> // <reference no-default-lib="true" />
> // <reference lib="esnext" />
765,771c765,771
<       Reader,
<       ReaderSync,
<       Writer,
<       WriterSync,
<       Seeker,
<       SeekerSync,
<       Closer {
---
>     Reader,
>     ReaderSync,
>     Writer,
>     WriterSync,
>     Seeker,
>     SeekerSync,
>     Closer {
1947c1947
<      * 
---
>      *
1950c1950
<      * 
---
>      *
```
</details>

Using this deduction as a basis, this updates the type declaration files by copying from the [latest Deno release `1.31.2`](https://github.com/denoland/deno/releases/tag/v1.31.2):

1. https://github.com/denoland/deno/blob/v1.31.2/cli/tsc/dts/lib.deno.ns.d.ts
2. https://github.com/denoland/deno/blob/v1.31.2/ext/net/lib.deno_net.d.ts

and replaces the [lib](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-lib-) reference [in the first file](https://github.com/denoland/deno/blob/v1.31.2/cli/tsc/dts/lib.deno.ns.d.ts#L5) with a relative [path](https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-path-) reference.

2023-03-15 10:32 UTC, jsejcksn commented on lib/deno/lib.deno.ns.d.ts
> +/// <reference path="./lib.deno_net.d.ts" />
Manually modified to use a relative path reference

2023-03-17 03:22 UTC, evanw requested changes
This PR introduces type errors, and so will not be merged as-is (see CI for details).

2023-03-17 05:16 UTC, evanw commented
After looking into this a bit, it looks like Deno's type declarations have been changed into many files, which is a bit unwieldy to keep up to date. It also looks like I should be using the `deno types` command instead of checking these type declarations in at all.

2023-03-17 05:46 UTC, closed without merging

2023-03-17 05:49 UTC, evanw commented
Ok I have switched esbuild over to using `deno types`. The CLI help for this command says the following:

```
$ deno help types
deno-types 
Print runtime TypeScript declarations.

  deno types > lib.deno.d.ts

The declaration file could be saved and used for typing information.

USAGE:
    deno types [OPTIONS]

OPTIONS:
    -h, --help
            Print help information

    -q, --quiet
            Suppress diagnostic output

        --unstable
            Enable unstable features and APIs
```

So this command is intended to be used like this. This way the type definitions should always match the minimum version of Deno that esbuild supports (as represented by the Deno version that esbuild runs against in CI) without needing to include Deno's API evolution in esbuild's git history.

2023-03-17 09:01 UTC, jsejcksn commented
@evanw Thanks for providing a bit of clarity.

I thought you might have intentionally included only the Deno namespace types in attempt to [prevent a type-checking conflict with the vanilla TS DOM library types](https://deno.land/manual@v1.31.3/advanced/typescript/configuration#using-the-lib-property) in a custom configuration. Again — there's no documentation for how the types were created or used... but after seeing the test failure, it is now more clear.

> After looking into this a bit, it looks like Deno's type declarations have been changed into many files, which is a bit unwieldy to keep up to date. It also looks like I should be using the `deno types` command instead of checking these type declarations in at all.

If the goal is type-check with all of the Deno types, then — as you observed — you can use the `deno types` command from Deno CLI to generate a bundled type declaration file. An identical file is also available as an artifact in every [release](https://github.com/denoland/deno/releases) — so if a certain version is desired, it might be simpler to download it instead of needing to install that specific version of Deno and generate it.

The URL format is like this:

```
https://github.com/denoland/deno/releases/download/{TAGNAME}/lib.deno.d.ts
```

So, for example, the file which corresponds to the [`v1.31.3`](https://github.com/denoland/deno/releases/tag/v1.31.3) release is at:

<pre><code><a href="https://github.com/denoland/deno/releases/download/v1.31.3/lib.deno.d.ts">https://github.com/denoland/deno/releases/download/v1.31.3/lib.deno.d.ts</a></pre></code>

<details>
<summary>
I used this GraphQL query and it looks like the file starts to appear in release <code>v0.39.0</code> and later:</summary>

```gql
query DenoDts($after: String) {
  repository(name: "deno", owner: "denoland") {
    releases(
      orderBy: {field: CREATED_AT, direction: ASC}
      first: 100
      after: $after
    ) {
      pageInfo {
        startCursor
        endCursor
      }
      nodes {
        releaseAssets(first: 100, name: "lib.deno.d.ts") {
          nodes {
            downloadUrl
          }
        }
        tagName
        createdAt
      }
    }
  }
}
```
</details>