added new runImpl that takes plugins
evanw/esbuild pull request #3539
Opened 2023-12-12 09:15 UTC by edewit

In order to build my own version of esbuild with pre installed go plugins. 
I've added this method to call the cli with plugins

Signed-off-by: Erik Jan de Wit <erikjan.dewit@gmail.com>

2023-12-21 10:37 UTC, ia3andy commented
Thanks for creating this PR @edewit, this will help a lot!

2023-12-21 10:47 UTC, ia3andy requested changes

2023-12-21 10:47 UTC, ia3andy commented on pkg/cli/cli_impl.go
> +		// buildOptions.Plugins = append(buildOptions.Plugins, scssPlugin)
@edewit this can be removed right?

2023-12-21 10:48 UTC, ia3andy commented on pkg/cli/cli_impl.go
> +		// buildOptions.Plugins = append(buildOptions.Plugins, scssPlugin)
```suggestion
```

2024-01-24 09:14 UTC, ia3andy commented
Hey @evanw, 

Could you consider getting this in, it would allow us to package our[ own CLI](https://github.com/mvnpm/esbuild) with plugins (scss) using normal GO import instead of forking the whole repository.

Cheers!

2024-05-06 14:32 UTC, ia3andy commented
@evanw ping!

2024-06-18 16:07 UTC, Rattlyy commented
bump :)

2024-06-24 15:25 UTC, ia3andy commented
@evanw any reason not to get this in?

2024-06-25 23:00 UTC, evanw commented
Hey, thanks for the bump. There's no reason to not get this in. I think something like this makes sense and I'm supportive of it. The only reason it hasn't gotten in yet is that I haven't put aside the time yet to do the PR (i.e. think about the approach, make any changes, land it, and ship it).

2024-06-26 08:04 UTC, ia3andy commented
Hey @evanw, that's a very good news! Thanks.

It seems this very basic PR is already enough for our use-case at least, do you have something else in mind?

2024-06-30 16:42 UTC, evanw commented
There are several approaches to this. In general `RunWith*` functions are not a great approach to extending APIs with many optional parameters, as there could be a combinatorial explosion of options (and therefore of functions). That's why esbuild's API generally takes structs instead of individual parameters. Other approaches could be to require you to separate parsing the API options from using them in this scenario, or to provide a callback to modify the CLI options after they are parsed but before they are used. However, it could also be ok to take the approach you're proposing as plugins are somewhat of a special case (one of the few API parameters that can't be configured with the CLI).

2024-06-30 18:26 UTC, merged

2024-07-01 06:53 UTC, ia3andy commented
Thanks!